#! /bin/sh
### BEGIN INIT INFO
# Provides:          voltronic-fcgi-control
# Required-Start:    $all
# Required-Stop:     
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Control voltronic fast-cgi processes
### END INIT INFO

PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/opt/bin

. /lib/init/vars.sh
. /lib/lsb/init-functions

case "$1" in
  start)
    log_begin_msg "Starting voltronic fast-cgi deamons"

    /opt/voltronic-web/voltronic-fcgi-serial-control
    /opt/voltronic-web/voltronic-fcgi-usb-control

    log_end_msg $?
    exit 0
    ;;
  stop)
    log_begin_msg "Stopping voltronic fast-cgi deamons"

    /opt/voltronic-web/voltronic-fcgi-serial-control stop
    /opt/voltronic-web/voltronic-fcgi-usb-control stop

    log_end_msg $?
    exit 0
    ;;
  *)
    echo "Usage: /etc/init.d/voltronic-fcgi-control {start|stop}"
    exit 1
    ;;
esac
