#!/usr/bin/env bash

# https://stackoverflow.com/questions/12025790/how-do-i-write-a-watchdog-daemon-in-bash
PIDFILE="/tmp/voltronic-fcgi.pid"
if [ x"$1" = x-daemon ]; then
  if test -f "$PIDFILE"; then exit; fi
  echo $$ > "$PIDFILE"
  trap "rm '$PIDFILE'" EXIT SIGTERM
  while true; do
    LD_LIBRARY_PATH=/usr/local/lib spawn-fcgi -p 9002 -n /opt/voltronic-fcgi-interface/voltronic_fcgi_hidraw &
    wait
  done
elif [ x"$1" = x-stop ]; then
  kill `cat "$PIDFILE"`
else
  nohup "$0" -daemon > /tmp/voltronic-fcgi-control.out 2> /tmp/voltronic-fcgi-control.err < /dev/null &
fi
